
export default () => ({
  KAFKAJS_DEBUG_PROTOCOL_BUFFERS: Deno.env.get("KAFKAJS_DEBUG_PROTOCOL_BUFFERS"),
  KAFKAJS_DEBUG_EXTENDED_PROTOCOL_BUFFERS:
    Deno.env.get("KAFKAJS_DEBUG_EXTENDED_PROTOCOL_BUFFERS"),
});
